all:
  children:
    ansible:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: ubuntu
    prod:
      vars:
        env: prod
        ansible_user: ubuntu
        ansible_password: ubuntu
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'


      hosts:
        worker03:
          ansible_host: 172.31.27.144
          hostname: AnsibleWorker03
        worker02:
          ansible_host: 172.31.84.218

          hostname: AnsibleWorker02
        worker04:
          ansible_host: 172.31.92.82
          hostname: AnsibleWorker04
          ansible_user: centos
          ansible_password: centos
        worker05:
          ansible_host: 172.31.94.195
          hostname: AnsibleWorker05
          ansible_user: centos
          ansible_password: centos

        worker-centos:
          ansible_host: 172.31.85.67
          hostname: AnsibleWorkerCentos
          ansible_user: centos
          ansible_password: centos

