all:
  children:
    ansible:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: ubuntu
    prod:
      vars:
        env: prod
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      hosts:
        worker03:
          ansible_host: 172.31.27.144
          hostname: AnsibleWorker03
          ansible_user: ubuntu
        worker02:
          ansible_host: 172.31.84.218
          ansible_user: ubuntu
          hostname: AnsibleWorker02
